<?php

/***********************************
 * views for entityobjects.com
 * /download.php 
 *
 * @author  mgill
 ***********************************
*/			
$root = realpath($_SERVER['DOCUMENT_ROOT']);
require_once $root."/include/view/page/index/head.inc";
require_once $root."/include/view/page/index/nav.inc";
require_once "downloadfiles.inc";
require_once $root."/include/view/page/index/foot.inc";

?>
