<?php

/***********************************
 * views for entityobjects.com
 * /admin/index.php 
 *
 * @author  mgill
 ***********************************
*/			
require_once "head.inc";
require_once "nav.inc";
require_once "login.inc";
require_once "home.inc";
require_once "inbox.inc";
require_once "contact.inc";
require_once "deletecontact.inc";
require_once "findcontacts.inc";
require_once "foot.inc";

?>
