<?php

/***********************************
 * about.inc 
 * @author  mgill
 ***********************************
*/			
function about()  
{
?>
  <section id="about">
    <div class="container">
      <div class="center">
        <div class="col-md-6 col-md-offset-3">
          <h2><br></h2>
          <p class="lead"><h3><b>A small & simple ORM solution for PHP</b></h3></p>
          <br><h3>1 Design your database</h3>
          <h3>2 Run the model builder</h3>
          <h3>3 Behold a beautiful PHP model</h3>
          <br><h3>Make the world a little bit better...</h3>
          <center>
	    <a href="/download/">
	      <button type="submit" name="submit" class="btn btn-primary btn-lg" >DOWNLOAD NOW</button>
	    </a>
	  </center>
          <br>
        </div>
      </div>
    </div>	
  </section>
<?php
}
?>
